version: "3.9"
   
services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations api && python manage.py migrate && python manage.py runcrons && python manage.py runserver 0.0.0.0:8000"
    container_name: youtube-api
    volumes:
      - .:/code
    ports:
      - "8000:8000"