# Generated by Django 3.2.6 on 2021-08-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=500, null=True)),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
